config/routes.rb
PhotographyWebsite::Application.routes.draw do

  devise_for :users, :skip => :registrations
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "photo/sorted"  
 
  get "photo/index"

  get "photo/show"

  get "photo/kitchen_and_food"

  get "photo/black_and_white"

  get "pages/home"

  get "pages/about"

  get "pages/contact"

  post "pages/email_erik"

  get "pages/entry"
  
  get "pages/comissions"

   root :to => 'pages#entry'

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  attr_accessible :description, :id, :title, :price, :url, :type, :tag_ids, :image_type, :color_type

  scope :black_and_white, where(color_type: "black and white")  
    
  default_scope order('created_at DESC')

  validates :title, :url, presence: true, uniqueness: true

  has_and_belongs_to_many :tags, uniq: true


end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :description, :name, :photo_ids
  validates :name, presence: true
  has_and_belongs_to_many :photos, uniq: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

#  layout "first_page", :only => :entry
#  should no longer need to use above

  def home
  @photos = Photo.all
  end

  def about
  @photos = Photo.all
  end

  def contact
  @photos = Photo.all
  end

  def email_erik
    if params[:mail_sender] != ''
      #removed .deliver from below, and now it works
      # used to say result = Contact ErikMailer.email_erik(params).deliver and it used to fucking work
      ContactErikMailer.email_erik(params).deliver
      render :text => "$('p#message_sent').text('Well done')"
    else
      render :text => "$('p#message_sent').text('Sorry, try again')"
    end
  end

  def entry
  @photos = Photo.all
  end

  def comissions
  @photos = Photo.all
  end

end

app/controllers/photo_controller.rb
class PhotoController < ApplicationController

  def sorted
  @photos = Photo.all
  @tag = Tag.find(params[:id])
  end

  def index
  @photos = Photo.all rescue []
#  @black_and_white_photos = Photo.black_and_white
 # @food_photos = Tag.find_by_name("Kitchen and food")
  end

  def new
  @photo = Photo.new
  end

  def edit
  @photo = Photo.find(params[:id])
  end

  def show
  @photo = Photo.find(params[:id])
  end

  def update

  end

  def destroy
  @photo = Photo.find(params[:id])
  @photo.destroy
  end

  def kitchen_and_food
  @photos = Tag.find_by_name("Kitchen and food").photos
  render :index
  end

  def black_and_white
  @photos = Photo.black_and_white
  render :index
  end

end

app/controllers/tag_controller.rb
class TagController < ApplicationController
  def index
  @tags = Tag.all
  end

  def new
  @tag = Tag.new
  end

  def edit
  @tag = Tag.find(params[:id])
  end

  def show
  @tag = Tag.find(params[:id])
  end

  def update
 
  end

  def destroy
  @tag = Tag.find(params[:id])
  @tag.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/layouts/_footer.html.erb
<footer>
   <ul>
    <li><%= link_to 'About', pages_about_path %></li>
    <li><%= link_to 'Contact', pages_contact_path %></li>
    <li><%= link_to 'Home', pages_home_path %></li>
    <li><%= link_to 'Photographs', photo_index_path %></li>
  </ul>
 </footer>

app/views/layouts/_header.html.erb
<header>
<h3> I am the header </h3>
<%= image_tag "oxalis_field.jpg", :size => "100x75", :class => "img-polaroid" %>
</header>

app/views/layouts/_shim.html.erb
 <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photography Website</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div>
      <% if false %>
      <div class="notice"><%= notice %></div>
      <% end %>
      <% if alert %>
      <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    
    <div class="contains">
      <div class="holder">
	<div class="navigation">
	  <ul class="nav">
	    <li id="erik"><%= link_to "Erik Lucero Photography", root_path %></li>
            <li><%= link_to "Comissions", pages_comissions_path %></li>
            <li><%= link_to "Profile", pages_about_path %></li>
            <li id="photographs"><%= link_to "Photographs", photo_index_path %></li>
            <li><%= link_to "Contact", pages_contact_path %></li>
	  </ul>
	</div>
      </div>
      
      <div class="drop">
	<div class="navigation">
	  <ul class="nav">
            <li><%= link_to "Kitchen and Food", photo_kitchen_and_food_path %></li>
            <li><%= link_to "Black and white", photo_black_and_white_path %></li>
            <li><%= link_to "All", photo_index_path %></li>
	  </ul>
	</div>
      </div>
   <!-- </div> moved this to allow jquery to work -->
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/first_page.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photography Website</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "entry" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <div>
    <% if notice %>
      <p class="notice"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert"><%= alert %></p>
    <% end %>
  </div>
  <div>

<%= yield %>

  </div>
  <%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/layouts/main_site.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photography Website</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <div>
      <% if false %>
      <div class="notice"><%= notice %></div>
      <% end %>
      <% if alert %>
      <p class="alert"><%= alert %></p>
      <% end %>
    </div>
    
    <div class="contains">
      <div class="holder border">
	<div class="navigation">
	  <ul class="nav">
	    <li id="erik"><%= link_to "Erik Lucero Photography", root_path %></li>
            <li><%= link_to "Comissions", pages_comissions_path %></li>
            <li><%= link_to "Profile", pages_about_path %></li>
            <li id="photographs"><%= link_to "Photographs", photo_index_path %></li>
            <li><%= link_to "Contact", pages_contact_path %></li>
	  </ul>
	</div>
      </div>
      
      <div class="drop border">
	<div class="navigation">
	  <ul class="nav">
            <li><%= link_to "Pictures!", photo_index_path %></li>
            <li><%= link_to "More", photo_index_path %></li>
            <li><%= link_to "Even more", photo_index_path %></li>
	  </ul>
	</div>
      </div>
   <!-- </div> moved this to allow jquery to work -->
    
    <%= yield %>
    </div>
  </body>
</html>

app/views/pages/about.html.erb
<h1 class="center">Profile</h1>
<%= image_tag "me_in_shades.jpg", id: "profile_pic" %>
<p class="profile">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas eget velit elit. Quisque fringilla nibh a orci vulputate ultricies. Curabitur in eros id sem feugiat pulvinar. Nullam tempus aliquet nisi eget adipiscing. Nunc lacinia nisi ac nisl aliquam hendrerit. Quisque sollicitudin accumsan euismod. Nunc sapien sem, sodales id aliquam non, iaculis rutrum orci. Nulla pharetra adipiscing porttitor. Mauris pharetra, sem eu sagittis rutrum, magna dui dictum metus, a auctor neque massa in purus. Duis ultricies volutpat nulla ac imperdiet. Mauris in pharetra nibh. Morbi vestibulum volutpat placerat.</p>
<p class="profile">Fusce eleifend convallis sollicitudin. Nulla at metus vitae nulla tempus bibendum id ut eros. Nunc varius, sapien convallis fermentum condimentum, dui urna varius est, sed blandit tellus erat in dui. Etiam in odio vitae est volutpat rhoncus eget quis purus. Vivamus congue nibh faucibus erat aliquet fermentum gravida nunc molestie. Integer quis arcu in metus consequat malesuada. Duis eu erat massa, a laoreet justo. Ut eleifend feugiat auctor. Vestibulum lacus erat, sodales quis iaculis sed, sagittis nec ante. Donec quis fermentum mi. Integer in libero lectus. Nam ac blandit urna. Aenean commodo libero in erat rutrum eget blandit lectus consectetur. Sed id bibendum eros. Sed nisi ipsum, pretium eget vehicula sit amet, suscipit quis nulla.</p>

app/views/pages/comissions.html.erb
<div class="paragraphs">
<h1 class="center">Comissions</h1>
<%= image_tag "WagonBike.jpg", id: "comissions_pic" %>
  <p class="comissions"> Aenean luctus tortor eget quam fringilla eu lacinia leo hendrerit. Nulla rutrum imperdiet nulla, vitae dapibus metus aliquet non. Proin pulvinar placerat turpis, ac vulputate metus luctus a. Praesent aliquet lobortis urna, non faucibus eros molestie vitae. Sed dictum dignissim ullamcorper. Nullam posuere posuere dui, id iaculis purus mattis in. Etiam nec ligula libero, sagittis sodales ipsum. Donec vulputate lacinia massa et vestibulum. Ut placerat justo at nunc vulputate pellentesque.</p>
  <p class="comissions"> Cras nibh dui, tristique sed eleifend ut, accumsan a quam. Etiam feugiat, enim quis tincidunt hendrerit, velit mi interdum eros, vitae porta ipsum lorem aliquam justo. Sed scelerisque vulputate vulputate. Nulla et quam in tortor vehicula facilisis eu non quam. Donec mattis nulla justo. Nam vitae leo eu justo accumsan rhoncus. In at sapien in augue sagittis placerat lobortis in elit. Pellentesque imperdiet est ante, vel mattis elit. Aliquam aliquet mollis tristique. Vivamus ac sem leo. Maecenas tincidunt dictum faucibus. Aliquam libero velit, pharetra vitae consequat vel, dapibus accumsan lectus. Maecenas commodo enim nec arcu auctor vel facilisis libero vehicula. Mauris imperdiet auctor consequat. In ipsum velit, convallis et eleifend eu, semper ut sapien.</p>
</div>

app/views/pages/contact.html.erb
<h1 class="center">Contact me</h1>
<p id="message_sent" class="center">Find me in app/views/pages/contact.html.erb</p>
<%= form_tag({action: 'email_erik'}, :remote => true, 'data-type' => 'script') do %>
  <input id="mail_sender" name="mail_sender" type="email" placeholder="Your email address"/>
  <input id="mail_subject" name="mail_subject" type="text" placeholder="Subject"/>
  <textarea id="mail_content" name="mail_content" placeholder="Your message"></textarea>
  <input id="send_mail" type="submit" value="Send" />
<% end %>

app/views/pages/entry.html.erb
<%= javascript_include_tag "entry" %>


<div id="bg">
  <% @photos.each do |photo| %>
  <% if photo.color_type == "color" %>
    <% if photo.image_type == "landscape" %>
      <%= image_tag photo.url, class: "color" %>
    <% end %>
  <% else %>
    <% if photo.image_type == "landscape" %>
      <%= image_tag photo.url, class: "black_and_white" %>
      <% end %>
    <% end %>
  <% end %>


</div>
</div>
<div id="button_holder">
  <div id="button_center">
    <btn id="color_button">color</btn>
    <btn id="black_and_white_button">black and white</btn>
  </div>
</div>

app/views/pages/home.html.erb
<h1>Photography Website</h1>


<div id="slideshow">
  <% @photos.each do |p| %>
  <div>
    <%= link_to(image_tag(p.url), { controller: "photo", action: "show", id: "#{p.id}" }, class: "crop slideshow") %>
  </div>
  <% end %>
</div>

app/views/photo/destroy.html.erb
<h1>Photo#destroy</h1>
<p>Find me in app/views/photo/destroy.html.erb</p>

app/views/photo/edit.html.erb
<h1>Photo#edit</h1>
<p>Find me in app/views/photo/edit.html.erb</p>

app/views/photo/index.html.erb
<div id="display">
  <p>Put a default pretty image here</p>
</div>
<div id="slider">


  <ul id="thumbnails">
      <% @photos.each do |p| %>
      <% if p.image_type == "landscape" %>
      <li class="nail"><%= image_tag "#{p.url}", class: "thumb crop" %></li>
      <% else if p.image_type == "portrait" %>
      <li class="nail"><%= image_tag "#{p.url}", class: "thumb crop portrait" %></li>
      <% end %>
      <% end %>
      <% end %>
  </ul>


</div>
  <btn id="click-back"><b>Back</b></btn>
  <btn id="click-forward"><b>Forward</b></btn>

app/views/photo/new.html.erb
<h1>Photo#new</h1>
<p>Find me in app/views/photo/new.html.erb</p>

app/views/photo/show.html.erb
<h1 class="center">Photo#show</h1>
<p class="center">Find me in app/views/photo/show.html.erb</p>
<div>
  <title><%= @photo.title %></title>
  <div>
    <div class="image main"><%= image_tag "#{@photo.url}" %></div>
    <span class="description"><%= @photo.description %></span>
  </div>
   <p><%= link_to "Back", photo_index_path %></p>
   <p>You will need to fix the Back, so it goes to where the user actually was.  Also, please make the css nice.</p>
</div>

app/views/photo/sorted.html.erb
<%= render 'layouts/header' %>
<p> content </p>
<

<%= render 'layouts/footer' %>

app/views/photo/update.html.erb
<h1>Photo#update</h1>
<p>Find me in app/views/photo/update.html.erb</p>

app/views/tag/destroy.html.erb
<h1>Tag#destroy</h1>
<p>Find me in app/views/tag/destroy.html.erb</p>

app/views/tag/edit.html.erb
<h1>Tag#edit</h1>
<p>Find me in app/views/tag/edit.html.erb</p>

app/views/tag/index.html.erb
<h1>Tag#index</h1>
<p>Find me in app/views/tag/index.html.erb</p>

app/views/tag/new.html.erb
<h1>Tag#new</h1>
<p>Find me in app/views/tag/new.html.erb</p>

app/views/tag/show.html.erb
<h1>Tag#show</h1>
<p>Find me in app/views/tag/show.html.erb</p>

app/views/tag/update.html.erb
<h1>Tag#update</h1>
<p>Find me in app/views/tag/update.html.erb</p>